/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FirstStep: typeof import('./src/components/firstStep.vue')['default']
    MainComponent: typeof import('./src/components/mainComponent.vue')['default']
    SecondStep: typeof import('./src/components/secondStep.vue')['default']
  }
}
